### ISSUE TITLE
Automating Pods-Acknowledgements.plist copy

### ISSUE THREAD

**Issue by billyto** [vtourraine/VTAcknowledgementsViewController#20]
If you want to automatically copy Pods-Acknowledgements, there are two options:

**Add a hook to the Podfile:**

```
post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Pods-Acknowledgements.plist', 'Pods-Acknowledgements.plist', :remove_destination => true)
end
```

_or_

**Add a new run script build phase at the end of your target build phases with the following line:**

```
cp ${SRCROOT}/Pods/Pods-acknowledgements.plist ${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/Pods-acknowledgements.plist
```

**Comment by natanrolnik** [comment]
Adding a hook to the Podfile changed, and it should be:

```
post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods/Pods-Acknowledgements.plist', 'Pods-Acknowledgements.plist', :remove_destination => true)
end
```

**Comment by Perjan** [comment]
Guys, these don't work anymore since cocoapods v1.0.0, because of the "abstract_target" definition.

**Comment by lolgear** [comment]
anybody, how does it help to copy acknowledgements to project directory? Which of scripts in build target would put this file in archive/app on archive/build action?
