### ISSUE TITLE
New location of Pods-acknowledgements.plist?

### ISSUE THREAD

**Issue by chrisballinger** [vtourraine/VTAcknowledgementsViewController#28]
As of Cocoapods 0.35.0:

Project root -> Pods -> Target Support Files -> Pods -> Pods-acknowledgements.plist

**Comment by dennisreimann** [comment]
awesome, thanks for the hint!

**Comment by vtourraine** [comment]
I’ve updated the README accordingly. Thanks for pointing that out! :+1:
