### ISSUE TITLE
Update installation instructions to reflect new acknowledgements.plist file location.

### ISSUE THREAD

**Issue by brunophilipe** [vtourraine/VTAcknowledgementsViewController#31]
From the [CocoaPods GitHub](https://github.com/CocoaPods/CocoaPods/issues/2717).
The Pods directory has been reorganised, and the acknowledgements.plist file has been moved.

The new location is:
`Pods/Target Support Files/Pods-{project}/Pods-{project}-acknowledgements.plist`

**Comment by vtourraine** [comment]
I’ve updated the README accordingly. Thanks for pointing that out! :+1:
