### ISSUE TITLE
please release a new version

### ISSUE THREAD

**Issue by simpleapples** [vtourraine/VTAcknowledgementsViewController#35]
hi,
please release a new version with simplified chinese translation. i'd like add it to my project with pods. thx.

**Comment by vtourraine** [comment]
Hey, thanks for the heads-up. I was still waiting for more feedback on the new header label, but in the meantime, you can use `pod 'VTAcknowledgementsViewController', :head` in your Podfile to get the latest version.

**Comment by vtourraine** [comment]
Version 0.14 is now available from the CocoaPods master repo.

https://github.com/vtourraine/VTAcknowledgementsViewController/releases/tag/0.14
