### ISSUE TITLE
Pod version numbers

### ISSUE THREAD

**Issue by chrisballinger** [vtourraine/VTAcknowledgementsViewController#36]
Would be useful if we could enable the display of Pod version numbers in addition to their name.

**Comment by vtourraine** [comment]
That would be interesting, yes! Unfortunately, this info isn’t part of the usual `plist` file generated by CocoaPods, so I’m not sure how we could implement that (without managing additional files).

We could import the `Podfile.lock`, for instance, and parse the versions from there. But that seems like a lot of troubles, for something that isn’t central to this pod (“acknowledgements”).

**Comment by chrisballinger** [comment]
Hmm perhaps it can be added upstream: https://github.com/CocoaPods/CocoaPods/issues/3391

**Comment by vtourraine** [comment]
So there’s this official plugin (linked in this aforementioned issue) that has been in development for more than a year now. It totally makes sense to pursue this kind of development there. I still think that this pod here has its place, so it’s good for everyone that these two have a slightly different approach.
