### ISSUE TITLE
iPad landscape screen filling

### ISSUE THREAD

**Issue by davidjupijnsping** [vtourraine/VTAcknowledgementsViewController#37]
I just implemented your pod and it's really nice and saves me some time so thanks for that!

The iPad app I'm currently working on only supports landscape orientation but the VTAcknowledgementViewController text doesn't fill the full size of the screen. It kind of looks like it just uses the 768 instead of the 1024 it has available. Could you take a look at this?

Btw it's not a deal breaker so I will still use it if you decide to not fix it. :)

**Comment by davidjupijnsping** [comment]
Never mind I just found out that it has nothing to do with your code but the actual license text.

**Comment by vtourraine** [comment]
Ha, I was going to say that it might be related to modal presentation mode (form sheet, page sheet, etc). Nevermind, I’m glad you’ve figured it out.
