### ISSUE TITLE
Custom font for header, footer and cell?

### ISSUE THREAD

**Issue by claesjacobsson** [vtourraine/VTAcknowledgementsViewController#38]
Thanks for this library! 

It would be fantastic to be able to set a custom font to header text, footer text and the cells. Is that something that you are working on or would you like a pull request?

Thanks!
Claes

**Comment by claesjacobsson** [comment]
Sent you a PR :-)

**Comment by vtourraine** [comment]
c.f. https://github.com/vtourraine/VTAcknowledgementsViewController/pull/39
