### ISSUE TITLE
The `textView` is not initialized on `init`

### ISSUE THREAD

**Issue by ignazioc** [vtourraine/VTAcknowledgementsViewController#42]
The release 0.15 removed the `textViewFont` property, replaced with a more flexible `textView`.

This textview is created inside the `loadView` method of the `VTAcknowledgementViewController` class. This means that is not possible to customize ad usual in the `didSelectRowAtIndexPath:` 

 ``` objc
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    VTAcknowledgement *acknowledgement = self.acknowledgements[indexPath.row];
    VTAcknowledgementViewController *viewController = [[VTAcknowledgementViewController alloc] initWithTitle:acknowledgement.title text:acknowledgement.text];
    viewController.textView.font = [UIFont ebk_font:EBKFontTypeNormal]; //At this point the textView is nil.
}

```

**Comment by levigroker** [comment]
You may be able to work around this by forcing the view to load before accessing the textView. i.e. after initialization but before setting the font, simply insert the line `[viewController view];`

**Comment by ignazioc** [comment]
Yes, of course and this is how I fixed on my app, but it should be solved into the library

**Comment by levigroker** [comment]
👍

**Comment by vtourraine** [comment]
Sorry I’m late to the party. That’s actually the expected view controller life cycle (I know, it’s a bit messy between `initWithCoder:`, Storyboard Segues, etc). Loading views belongs to `loadView`.

That said, iOS 9 properly adresses the issue you’re having, with the new `loadViewIfNeeded` method on `UIViewController`. Before that, the workaround already mentioned here seems reasonable.

**Comment by ignazioc** [comment]
I'm afraid that I don't agree.
If a ViewController exposes an UI element as a 'public' element, this should be available after the `init` method.
I.E. if you create a new instance of a `UITabBarViewController` you can immediately access to the `UITabBar` property.

**Comment by vtourraine** [comment]
That would probably be the most convenient way to do it, but I insist that expecting outlets to be initialized after the `init` is sometimes valid, _but not always_ (just look at Storyboard Segues, even if not everybody uses them, they exist).

So the most comprehensive solution might be to keep some kind of `textViewFont` property like before, that you could customize at any time, and let the controller configure itself accordingly. My problem with this approach is that it leads to a very large number of properties to configure every aspect of every subview.

I’d rather do something simpler, and ultimately easier to customize (with subclassing, for instance, if you need something very specific). That’s what I’m trying to enforce here, but I appreciate the feedback, and welcome any correction/improvement.

**Comment by ignazioc** [comment]
:+1:  Tank you for the effort spent on this repo. :bow:

**Comment by vtourraine** [comment]
:ok_hand:
