### ISSUE TITLE
iOS 9 bug causes application to crash when longpressing and tapping links

### ISSUE THREAD

**Issue by bernhard-eiling** [vtourraine/VTAcknowledgementsViewController#46]
After long pressing and afterwards tapping a link an application crashes.
This is apparently a iOS bug https://forums.developer.apple.com/thread/19480
The crash occurs only under iOS 9.0 and 9.1

Reproduction:

1. Open a detail view including a link.
2. Long press the link.
3. Tap the link.

**Comment by vtourraine** [comment]
Thanks for the bug report. I wasn’t aware of this problem, and I’m actually unable to reproduce it. I’m on iOS 9.2 (latest public release). Has it been fixed (this forums thread doesn’t tell)?

If that’s the case, I’m not sure if it’s worth adding extra code to handle this bug. Everyone on 9.0 and 9.1 can (and most likely, will) update to more recent versions. Does that seem fair?

**Comment by bernhard-eiling** [comment]
Hey @vtourraine thanks for responding that quick. We had an internal discussion about the issue and decided that we won't need a bugfix because, as you mentioned, most people will upgrade to at least 9.2

**Comment by vtourraine** [comment]
:+1:
