### ISSUE TITLE
Exclude certain pods?

### ISSUE THREAD

**Issue by skyline75489** [vtourraine/VTAcknowledgementsViewController#49]
I want to exclude some private pods. Anyway to do this?

**Comment by vtourraine** [comment]
The list of acknowledgements displayed by `VTAcknowledgementsViewController` mirrors the content of its `acknowledgements` array property.

``` objc
@property (nonatomic, strong, nullable) NSArray <VTAcknowledgement *> *acknowledgements;
```

This property is usually set by the view controller initializer, as a result of parsing the CocoaPods `plist` file. It’s not a `NSMutableArray`, but you can modify it separately, or even create a new array from scratch, and assign this new value to the `acknowledgements` property, before presenting the view controller.

Is that what you’re looking for?

**Comment by skyline75489** [comment]
Kind of...I was hoping for a more friendly API like:

`objective-c
vc.excludePods = @[@"SomePod"];
`

**Comment by vtourraine** [comment]
No, I think it’s better to keep the array property as a generic solution, which is easy to manipulate for custom results.

For instance, here’s a one-line solution to exclude a pod (not as succinct, I know):

``` objc
// Create view controller
viewController.acknowledgements = [viewController.acknowledgements filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@"title != %@", @"SomePod"]];
// Present view controller
```

**Comment by skyline75489** [comment]
Cool. This is actually a reasonable solution, I think.

**Comment by vtourraine** [comment]
:+1:
