### ISSUE TITLE
Navigation title optional for detail screen

### ISSUE THREAD

**Issue by muellerfa** [vtourraine/VTAcknowledgementsViewController#57]
Hi!

First of all, very nice work! Saves a lot of time! :-)

If you tap on one license in the overview table view, the detail screen will be shown. This view controller has the name of the VTAcknowledgement as title. It would be great if the view controller title could be optional.

Maybe you already solved this, but I hasn't found anything.

Best regards,
Fabian

**Comment by vtourraine** [comment]
Hi Fabian, and thanks for your feedback!

This title label is simply the system `title` property on `UIViewController`. If you want to hide it, you can just set this property to `nil`.

There is no global property to switch this off directly, so you’ll have to subclass and override some methods, but that seems like a very uncommon situation, so I don’t want to put this inside the library. Let me know if you need more help to implement that.
