### ISSUE TITLE
UINavigationBar title not centred

### ISSUE THREAD

**Issue by Xenero** [vtourraine/VTAcknowledgementsViewController#58]
For some reason, the backButton is ridiculously large and is preventing the title from being centred in some instances. This is only happening on the pod detail page.

**Comment by vtourraine** [comment]
Hi Brandon, and thanks a lot for the feedback!

Unfortunately, I’m unable to reproduce this issue. Is this happening on a specific configuration (device/iOS version)? With a specific code (for instance, does it happen with the “Tests” project included in this repo)?
