### ISSUE TITLE
Adding custom license

### ISSUE THREAD

**Issue by MasaruKitajima** [vtourraine/VTAcknowledgementsViewController#59]
I followed the instructions written in CocoaPods page as below.
```
VTAcknowledgement *customLicense = [[VTAcknowledgement alloc] init];
customLicense.title = NSLocalizedString(@"...", nil);
customLicense.text  = NSLocalizedString(@"...", nil);

viewController.acknowledgements = @[customLicense];
```
First problem is that `[[VTAcknowledgement alloc] init];` returns nil. I dig into VTAcknowledgement.m and found `init` returns nil and we need to use `initWithTitle:(NSString *) text:(NSString *) license(NSString *) instead. I recommend you to update the document both on GitHub and CocoaPods.

Second, in the issue #23, it's said that 

> You can create VTAcknowledgement instances, and assign a title and a text body, then reassign the NSArray *acknowledgements property on the VTAcknowledgementsViewController after the init. So adding non-cocoapods licenses should be easy.

So I wrote 
```
NSString *path = [[NSBundle mainBundle] pathForResource:@"Pods-TraLingo-acknowledgements" ofType:@"plist"];
VTAcknowledgementsViewController *ackViewController = [[VTAcknowledgementsViewController alloc]initWithPath:path];

VTAcknowledgement *customLicense = [[VTAcknowledgement alloc] initWithTitle:@"Prime Kobo LLC" text:strAboutPrimeKobo license:@"All rigths reserved 2017- Prime Kobo LLC"];
ackViewController.acknowledgements = @[customLicense];
```

But in this case, only added license is shown and no Pods license are shown.

How can I mix them together?

**Comment by vtourraine** [comment]
Hello Masaru, and thank you very much for the feedback!

First, about `init` returning `nil`. I believe that Xcode can tell you that the method is unavailable (the code is correctly annotated), but that depends on your warning configuration. But you’re right, that can be confusing. I’ll try to update the documentation, or maybe reconsider the existing initialisers.

Second, about the custom array. You just need to merge the default array (the licenses loaded from the plist file) with your custom licenses, like so:

``` objc
ackViewController.acknowledgements = [ackViewController.acknowledgements arrayByAddingObject:customLicense];
```

Or:

``` objc
ackViewController.acknowledgements = [ackViewController.acknowledgements arrayByAddingObjectsFromArray:@[customLicense]];
```

And by the way, you can simplify your code by replacing the first two lines with this:

``` objc
VTAcknowledgementsViewController *ackViewController = [[VTAcknowledgementsViewController alloc] initWithFileNamed:@"Pods-TraLingo-acknowledgements"];
```

I hope this will be useful to you. Please let me know if you have further questions.

**Comment by MasaruKitajima** [comment]
@vtourraine Thank you so much for your kind and detailed explanations.
It works fine! Again thank you so much.

As for `init` , I'm using Xcode 9 beta 6 and it doesn't tell me that method is unavailable.

And also thank you for your kind considering about the document!

Thank you so much for your very useful and important **VTAcknowledgementsViewController** !
