### ISSUE TITLE
Scroll bar isn't on correct position

### ISSUE THREAD

**Issue by smajekp** [vtourraine/VTAcknowledgementsViewController#62]
Scroll bar in license details is few points from right. On the licenses list is on good position. 

Device: iPhone 8
iOS 11.3.1

**Comment by vtourraine** [comment]
Thanks a lot for reporting this issue. The layout guides for readable content don’t automatically extend the text view insets, which was causing this scroll bar inconsistency. For now, my solution is to remove the readable content layout guides, and adjust the insets manually. Not perfect, but I think it’s better in most cases, and it addresses this specific problem.

You can test it now with the latest changes on master, and I’ll release a CocoaPods update soon.
