### ISSUE TITLE
how to change color of navigation back button

### ISSUE THREAD

**Issue by vkcldhkd** [vtourraine/VTAcknowledgementsViewController#65]
Thanks for making a good library.
I want to change the color of the navigation back button. But it did not change.
Help me...

``` swift
guard let openSourceVC = VTAcknowledgementsViewController.acknowledgementsViewController () else {return}
                
////// NOT CHANGE!!
openSourceVC.navigationController? .navigationBar.tintColor = .black
openSourceVC.navigationController? .navigationBar.barTintColor = .black
//////

openSourceVC.navigationItem.title = "SETTING_TEXT8" .localized ()
                
openSourceVC.headerText = ""
openSourceVC.footerText = ""
push (vc: openSourceVC)
```

**Comment by vtourraine** [comment]
Hello (and sorry for this late response 😅),

The problem in this code is that the `VTAcknowledgementsViewController` instance doesn’t have a navigation controller. So `openSourceVC.navigationController?` returns `nil`, and fails silently.

The fix would depend on your specific interface, but if the current view controller already has a navigation controller, it could be as simple as this:

``` swift
self.navigationController?.navigationBar.tintColor = .black
self.navigationController?.navigationBar.barTintColor = .black
```

**Comment by vkcldhkd** [comment]
My solution is to create a new ViewController!
1. Get the acknowledgments from the AcknowledgeListViewController.
2. binding Custom UI with acknowledgments 

``` swift
        let acknowListVC = AcknowListViewController()
        self.acknowledgements = acknowListVC.acknowledgements
        tableView.reloadData()
```

**Comment by vtourraine** [comment]
Glad to hear that you could find a suitable solution 👍
